name: .NET Core

on: [push]

env:
  AZURE_WEBAPP_NAME: ghvsl2020bar1970
  AZURE_GROUP_NAME: ghvsl2020l

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Build with dotnet
      run: dotnet build ./src/ghcorewebapp/ghcorewebapp.csproj --configuration Release
      
    - name: Package with dotnet
      run: dotnet publish ./src/ghcorewebapp/ghcorewebapp.csproj --configuration Release --output ./output
      
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: ghcorewebapp
        # Directory containing files to upload
        path: ./output
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CRED }}

      - run: |
          az group create -n ${{ env.AZURE_GROUP_NAME }} -l westus 
          az group deployment create -n ghaction -g ${{ env.AZURE_GROUP_NAME }} --template-file ./src/infra/azuredepoy.json

      # Azure logout 
      - name: logout
        run: |
          az logout
