name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet
      run: dotnet build ./src/ghcorewebapp/ghcorewebapp.csproj --configuration Release
    - name: Package with dotnet
      run: dotnet publish ./src/ghcorewebapp/ghcorewebapp.csproj --configuration Release
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: ghcorewebapp
        # Directory containing files to upload
        path: bin/Release/netcoreapp3.1/publish
